//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace BazusApi
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LessonPlan", Namespace="http://schemas.datacontract.org/2004/07/BazusApi")]
    public partial class LessonPlan : object
    {
        
        private BazusApi.Lesson[] LessonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BazusApi.Lesson[] Lessons
        {
            get
            {
                return this.LessonsField;
            }
            set
            {
                this.LessonsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lesson", Namespace="http://schemas.datacontract.org/2004/07/BazusApi")]
    public partial class Lesson : object
    {
        
        private string BuildingField;
        
        private System.DateTime EndTimeField;
        
        private string FieldOfStudyIdField;
        
        private string FieldOfStudyNameField;
        
        private string GroupNameField;
        
        private string InstructorField;
        
        private int LessonIdField;
        
        private string LessonNameField;
        
        private string LessonTypeField;
        
        private int RecruitmentYearField;
        
        private string RoomNumberField;
        
        private string SpecialtyIdField;
        
        private string SpecialtyNameField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldOfStudyId
        {
            get
            {
                return this.FieldOfStudyIdField;
            }
            set
            {
                this.FieldOfStudyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldOfStudyName
        {
            get
            {
                return this.FieldOfStudyNameField;
            }
            set
            {
                this.FieldOfStudyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instructor
        {
            get
            {
                return this.InstructorField;
            }
            set
            {
                this.InstructorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LessonId
        {
            get
            {
                return this.LessonIdField;
            }
            set
            {
                this.LessonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LessonName
        {
            get
            {
                return this.LessonNameField;
            }
            set
            {
                this.LessonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LessonType
        {
            get
            {
                return this.LessonTypeField;
            }
            set
            {
                this.LessonTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecruitmentYear
        {
            get
            {
                return this.RecruitmentYearField;
            }
            set
            {
                this.RecruitmentYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber
        {
            get
            {
                return this.RoomNumberField;
            }
            set
            {
                this.RoomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialtyId
        {
            get
            {
                return this.SpecialtyIdField;
            }
            set
            {
                this.SpecialtyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialtyName
        {
            get
            {
                return this.SpecialtyNameField;
            }
            set
            {
                this.SpecialtyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
}
namespace MobilePWSZService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News", Namespace="http://schemas.datacontract.org/2004/07/MobilePWSZService")]
    public partial class News : object
    {
        
        private string komunikatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string komunikat
        {
            get
            {
                return this.komunikatField;
            }
            set
            {
                this.komunikatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wydarzenia", Namespace="http://schemas.datacontract.org/2004/07/MobilePWSZService")]
    public partial class wydarzenia : object
    {
        
        private System.DateTime dataField;
        
        private long id_indexField;
        
        private int id_wydarzeniaField;
        
        private string trescField;
        
        private string tytulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id_index
        {
            get
            {
                return this.id_indexField;
            }
            set
            {
                this.id_indexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_wydarzenia
        {
            get
            {
                return this.id_wydarzeniaField;
            }
            set
            {
                this.id_wydarzeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tresc
        {
            get
            {
                return this.trescField;
            }
            set
            {
                this.trescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tytul
        {
            get
            {
                return this.tytulField;
            }
            set
            {
                this.tytulField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAuthenticate", ReplyAction="http://tempuri.org/IService1/GetAuthenticateResponse")]
    System.IAsyncResult BeginGetAuthenticate(string login, string password, string PasswordHash, System.AsyncCallback callback, object asyncState);
    
    bool EndGetAuthenticate(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetRegister", ReplyAction="http://tempuri.org/IService1/GetRegisterResponse")]
    System.IAsyncResult BeginGetRegister(string login, string password, string mail, System.AsyncCallback callback, object asyncState);
    
    bool EndGetRegister(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetPlan", ReplyAction="http://tempuri.org/IService1/GetPlanResponse")]
    System.IAsyncResult BeginGetPlan(string indeks, System.DateTime enteredDate, System.AsyncCallback callback, object asyncState);
    
    BazusApi.LessonPlan EndGetPlan(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetReset", ReplyAction="http://tempuri.org/IService1/GetResetResponse")]
    System.IAsyncResult BeginGetReset(string login, string mail, string passOld_passNew, System.AsyncCallback callback, object asyncState);
    
    bool EndGetReset(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNews", ReplyAction="http://tempuri.org/IService1/GetNewsResponse")]
    System.IAsyncResult BeginGetNews(System.AsyncCallback callback, object asyncState);
    
    MobilePWSZService.News[] EndGetNews(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetHash", ReplyAction="http://tempuri.org/IService1/GetHashResponse")]
    System.IAsyncResult BeginGetHash(string login, string password, System.AsyncCallback callback, object asyncState);
    
    string EndGetHash(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUpdatedPlan", ReplyAction="http://tempuri.org/IService1/GetUpdatedPlanResponse")]
    System.IAsyncResult BeginGetUpdatedPlan(string kierunek, string rok, System.AsyncCallback callback, object asyncState);
    
    string EndGetUpdatedPlan(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/AktualneNa7", ReplyAction="http://tempuri.org/IService1/AktualneNa7Response")]
    System.IAsyncResult BeginAktualneNa7(string indeks, string date, System.AsyncCallback callback, object asyncState);
    
    BazusApi.LessonPlan[] EndAktualneNa7(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DodajWydarzenie", ReplyAction="http://tempuri.org/IService1/DodajWydarzenieResponse")]
    System.IAsyncResult BeginDodajWydarzenie(string indeks, System.DateTime date, string tytul_tekst, System.AsyncCallback callback, object asyncState);
    
    string EndDodajWydarzenie(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetWydarzenia", ReplyAction="http://tempuri.org/IService1/GetWydarzeniaResponse")]
    System.IAsyncResult BeginGetWydarzenia(string indeks, System.AsyncCallback callback, object asyncState);
    
    MobilePWSZService.wydarzenia[] EndGetWydarzenia(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BazusApi.LessonPlan Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BazusApi.LessonPlan)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetResetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetResetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public MobilePWSZService.News[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((MobilePWSZService.News[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetHashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetUpdatedPlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetUpdatedPlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AktualneNa7CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public AktualneNa7CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BazusApi.LessonPlan[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BazusApi.LessonPlan[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DodajWydarzenieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public DodajWydarzenieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetWydarzeniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetWydarzeniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public MobilePWSZService.wydarzenia[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((MobilePWSZService.wydarzenia[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    private BeginOperationDelegate onBeginGetAuthenticateDelegate;
    
    private EndOperationDelegate onEndGetAuthenticateDelegate;
    
    private System.Threading.SendOrPostCallback onGetAuthenticateCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetRegisterDelegate;
    
    private EndOperationDelegate onEndGetRegisterDelegate;
    
    private System.Threading.SendOrPostCallback onGetRegisterCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetPlanDelegate;
    
    private EndOperationDelegate onEndGetPlanDelegate;
    
    private System.Threading.SendOrPostCallback onGetPlanCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetResetDelegate;
    
    private EndOperationDelegate onEndGetResetDelegate;
    
    private System.Threading.SendOrPostCallback onGetResetCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetNewsDelegate;
    
    private EndOperationDelegate onEndGetNewsDelegate;
    
    private System.Threading.SendOrPostCallback onGetNewsCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHashDelegate;
    
    private EndOperationDelegate onEndGetHashDelegate;
    
    private System.Threading.SendOrPostCallback onGetHashCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetUpdatedPlanDelegate;
    
    private EndOperationDelegate onEndGetUpdatedPlanDelegate;
    
    private System.Threading.SendOrPostCallback onGetUpdatedPlanCompletedDelegate;
    
    private BeginOperationDelegate onBeginAktualneNa7Delegate;
    
    private EndOperationDelegate onEndAktualneNa7Delegate;
    
    private System.Threading.SendOrPostCallback onAktualneNa7CompletedDelegate;
    
    private BeginOperationDelegate onBeginDodajWydarzenieDelegate;
    
    private EndOperationDelegate onEndDodajWydarzenieDelegate;
    
    private System.Threading.SendOrPostCallback onDodajWydarzenieCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetWydarzeniaDelegate;
    
    private EndOperationDelegate onEndGetWydarzeniaDelegate;
    
    private System.Threading.SendOrPostCallback onGetWydarzeniaCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetAuthenticateCompletedEventArgs> GetAuthenticateCompleted;
    
    public event System.EventHandler<GetRegisterCompletedEventArgs> GetRegisterCompleted;
    
    public event System.EventHandler<GetPlanCompletedEventArgs> GetPlanCompleted;
    
    public event System.EventHandler<GetResetCompletedEventArgs> GetResetCompleted;
    
    public event System.EventHandler<GetNewsCompletedEventArgs> GetNewsCompleted;
    
    public event System.EventHandler<GetHashCompletedEventArgs> GetHashCompleted;
    
    public event System.EventHandler<GetUpdatedPlanCompletedEventArgs> GetUpdatedPlanCompleted;
    
    public event System.EventHandler<AktualneNa7CompletedEventArgs> AktualneNa7Completed;
    
    public event System.EventHandler<DodajWydarzenieCompletedEventArgs> DodajWydarzenieCompleted;
    
    public event System.EventHandler<GetWydarzeniaCompletedEventArgs> GetWydarzeniaCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetAuthenticate(string login, string password, string PasswordHash, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAuthenticate(login, password, PasswordHash, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IService1.EndGetAuthenticate(System.IAsyncResult result)
    {
        return base.Channel.EndGetAuthenticate(result);
    }
    
    private System.IAsyncResult OnBeginGetAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        string PasswordHash = ((string)(inValues[2]));
        return ((IService1)(this)).BeginGetAuthenticate(login, password, PasswordHash, callback, asyncState);
    }
    
    private object[] OnEndGetAuthenticate(System.IAsyncResult result)
    {
        bool retVal = ((IService1)(this)).EndGetAuthenticate(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAuthenticateCompleted(object state)
    {
        if ((this.GetAuthenticateCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAuthenticateCompleted(this, new GetAuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAuthenticateAsync(string login, string password, string PasswordHash)
    {
        this.GetAuthenticateAsync(login, password, PasswordHash, null);
    }
    
    public void GetAuthenticateAsync(string login, string password, string PasswordHash, object userState)
    {
        if ((this.onBeginGetAuthenticateDelegate == null))
        {
            this.onBeginGetAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginGetAuthenticate);
        }
        if ((this.onEndGetAuthenticateDelegate == null))
        {
            this.onEndGetAuthenticateDelegate = new EndOperationDelegate(this.OnEndGetAuthenticate);
        }
        if ((this.onGetAuthenticateCompletedDelegate == null))
        {
            this.onGetAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthenticateCompleted);
        }
        base.InvokeAsync(this.onBeginGetAuthenticateDelegate, new object[] {
                    login,
                    password,
                    PasswordHash}, this.onEndGetAuthenticateDelegate, this.onGetAuthenticateCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetRegister(string login, string password, string mail, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRegister(login, password, mail, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IService1.EndGetRegister(System.IAsyncResult result)
    {
        return base.Channel.EndGetRegister(result);
    }
    
    private System.IAsyncResult OnBeginGetRegister(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        string mail = ((string)(inValues[2]));
        return ((IService1)(this)).BeginGetRegister(login, password, mail, callback, asyncState);
    }
    
    private object[] OnEndGetRegister(System.IAsyncResult result)
    {
        bool retVal = ((IService1)(this)).EndGetRegister(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetRegisterCompleted(object state)
    {
        if ((this.GetRegisterCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetRegisterCompleted(this, new GetRegisterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetRegisterAsync(string login, string password, string mail)
    {
        this.GetRegisterAsync(login, password, mail, null);
    }
    
    public void GetRegisterAsync(string login, string password, string mail, object userState)
    {
        if ((this.onBeginGetRegisterDelegate == null))
        {
            this.onBeginGetRegisterDelegate = new BeginOperationDelegate(this.OnBeginGetRegister);
        }
        if ((this.onEndGetRegisterDelegate == null))
        {
            this.onEndGetRegisterDelegate = new EndOperationDelegate(this.OnEndGetRegister);
        }
        if ((this.onGetRegisterCompletedDelegate == null))
        {
            this.onGetRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRegisterCompleted);
        }
        base.InvokeAsync(this.onBeginGetRegisterDelegate, new object[] {
                    login,
                    password,
                    mail}, this.onEndGetRegisterDelegate, this.onGetRegisterCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetPlan(string indeks, System.DateTime enteredDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetPlan(indeks, enteredDate, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BazusApi.LessonPlan IService1.EndGetPlan(System.IAsyncResult result)
    {
        return base.Channel.EndGetPlan(result);
    }
    
    private System.IAsyncResult OnBeginGetPlan(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string indeks = ((string)(inValues[0]));
        System.DateTime enteredDate = ((System.DateTime)(inValues[1]));
        return ((IService1)(this)).BeginGetPlan(indeks, enteredDate, callback, asyncState);
    }
    
    private object[] OnEndGetPlan(System.IAsyncResult result)
    {
        BazusApi.LessonPlan retVal = ((IService1)(this)).EndGetPlan(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetPlanCompleted(object state)
    {
        if ((this.GetPlanCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetPlanCompleted(this, new GetPlanCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetPlanAsync(string indeks, System.DateTime enteredDate)
    {
        this.GetPlanAsync(indeks, enteredDate, null);
    }
    
    public void GetPlanAsync(string indeks, System.DateTime enteredDate, object userState)
    {
        if ((this.onBeginGetPlanDelegate == null))
        {
            this.onBeginGetPlanDelegate = new BeginOperationDelegate(this.OnBeginGetPlan);
        }
        if ((this.onEndGetPlanDelegate == null))
        {
            this.onEndGetPlanDelegate = new EndOperationDelegate(this.OnEndGetPlan);
        }
        if ((this.onGetPlanCompletedDelegate == null))
        {
            this.onGetPlanCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPlanCompleted);
        }
        base.InvokeAsync(this.onBeginGetPlanDelegate, new object[] {
                    indeks,
                    enteredDate}, this.onEndGetPlanDelegate, this.onGetPlanCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetReset(string login, string mail, string passOld_passNew, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetReset(login, mail, passOld_passNew, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IService1.EndGetReset(System.IAsyncResult result)
    {
        return base.Channel.EndGetReset(result);
    }
    
    private System.IAsyncResult OnBeginGetReset(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string mail = ((string)(inValues[1]));
        string passOld_passNew = ((string)(inValues[2]));
        return ((IService1)(this)).BeginGetReset(login, mail, passOld_passNew, callback, asyncState);
    }
    
    private object[] OnEndGetReset(System.IAsyncResult result)
    {
        bool retVal = ((IService1)(this)).EndGetReset(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetResetCompleted(object state)
    {
        if ((this.GetResetCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetResetCompleted(this, new GetResetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetResetAsync(string login, string mail, string passOld_passNew)
    {
        this.GetResetAsync(login, mail, passOld_passNew, null);
    }
    
    public void GetResetAsync(string login, string mail, string passOld_passNew, object userState)
    {
        if ((this.onBeginGetResetDelegate == null))
        {
            this.onBeginGetResetDelegate = new BeginOperationDelegate(this.OnBeginGetReset);
        }
        if ((this.onEndGetResetDelegate == null))
        {
            this.onEndGetResetDelegate = new EndOperationDelegate(this.OnEndGetReset);
        }
        if ((this.onGetResetCompletedDelegate == null))
        {
            this.onGetResetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetResetCompleted);
        }
        base.InvokeAsync(this.onBeginGetResetDelegate, new object[] {
                    login,
                    mail,
                    passOld_passNew}, this.onEndGetResetDelegate, this.onGetResetCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetNews(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetNews(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MobilePWSZService.News[] IService1.EndGetNews(System.IAsyncResult result)
    {
        return base.Channel.EndGetNews(result);
    }
    
    private System.IAsyncResult OnBeginGetNews(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IService1)(this)).BeginGetNews(callback, asyncState);
    }
    
    private object[] OnEndGetNews(System.IAsyncResult result)
    {
        MobilePWSZService.News[] retVal = ((IService1)(this)).EndGetNews(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetNewsCompleted(object state)
    {
        if ((this.GetNewsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetNewsCompleted(this, new GetNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetNewsAsync()
    {
        this.GetNewsAsync(null);
    }
    
    public void GetNewsAsync(object userState)
    {
        if ((this.onBeginGetNewsDelegate == null))
        {
            this.onBeginGetNewsDelegate = new BeginOperationDelegate(this.OnBeginGetNews);
        }
        if ((this.onEndGetNewsDelegate == null))
        {
            this.onEndGetNewsDelegate = new EndOperationDelegate(this.OnEndGetNews);
        }
        if ((this.onGetNewsCompletedDelegate == null))
        {
            this.onGetNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNewsCompleted);
        }
        base.InvokeAsync(this.onBeginGetNewsDelegate, null, this.onEndGetNewsDelegate, this.onGetNewsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetHash(string login, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHash(login, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndGetHash(System.IAsyncResult result)
    {
        return base.Channel.EndGetHash(result);
    }
    
    private System.IAsyncResult OnBeginGetHash(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IService1)(this)).BeginGetHash(login, password, callback, asyncState);
    }
    
    private object[] OnEndGetHash(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndGetHash(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHashCompleted(object state)
    {
        if ((this.GetHashCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHashCompleted(this, new GetHashCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHashAsync(string login, string password)
    {
        this.GetHashAsync(login, password, null);
    }
    
    public void GetHashAsync(string login, string password, object userState)
    {
        if ((this.onBeginGetHashDelegate == null))
        {
            this.onBeginGetHashDelegate = new BeginOperationDelegate(this.OnBeginGetHash);
        }
        if ((this.onEndGetHashDelegate == null))
        {
            this.onEndGetHashDelegate = new EndOperationDelegate(this.OnEndGetHash);
        }
        if ((this.onGetHashCompletedDelegate == null))
        {
            this.onGetHashCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHashCompleted);
        }
        base.InvokeAsync(this.onBeginGetHashDelegate, new object[] {
                    login,
                    password}, this.onEndGetHashDelegate, this.onGetHashCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetUpdatedPlan(string kierunek, string rok, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetUpdatedPlan(kierunek, rok, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndGetUpdatedPlan(System.IAsyncResult result)
    {
        return base.Channel.EndGetUpdatedPlan(result);
    }
    
    private System.IAsyncResult OnBeginGetUpdatedPlan(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string kierunek = ((string)(inValues[0]));
        string rok = ((string)(inValues[1]));
        return ((IService1)(this)).BeginGetUpdatedPlan(kierunek, rok, callback, asyncState);
    }
    
    private object[] OnEndGetUpdatedPlan(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndGetUpdatedPlan(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetUpdatedPlanCompleted(object state)
    {
        if ((this.GetUpdatedPlanCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetUpdatedPlanCompleted(this, new GetUpdatedPlanCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetUpdatedPlanAsync(string kierunek, string rok)
    {
        this.GetUpdatedPlanAsync(kierunek, rok, null);
    }
    
    public void GetUpdatedPlanAsync(string kierunek, string rok, object userState)
    {
        if ((this.onBeginGetUpdatedPlanDelegate == null))
        {
            this.onBeginGetUpdatedPlanDelegate = new BeginOperationDelegate(this.OnBeginGetUpdatedPlan);
        }
        if ((this.onEndGetUpdatedPlanDelegate == null))
        {
            this.onEndGetUpdatedPlanDelegate = new EndOperationDelegate(this.OnEndGetUpdatedPlan);
        }
        if ((this.onGetUpdatedPlanCompletedDelegate == null))
        {
            this.onGetUpdatedPlanCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUpdatedPlanCompleted);
        }
        base.InvokeAsync(this.onBeginGetUpdatedPlanDelegate, new object[] {
                    kierunek,
                    rok}, this.onEndGetUpdatedPlanDelegate, this.onGetUpdatedPlanCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginAktualneNa7(string indeks, string date, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAktualneNa7(indeks, date, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    BazusApi.LessonPlan[] IService1.EndAktualneNa7(System.IAsyncResult result)
    {
        return base.Channel.EndAktualneNa7(result);
    }
    
    private System.IAsyncResult OnBeginAktualneNa7(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string indeks = ((string)(inValues[0]));
        string date = ((string)(inValues[1]));
        return ((IService1)(this)).BeginAktualneNa7(indeks, date, callback, asyncState);
    }
    
    private object[] OnEndAktualneNa7(System.IAsyncResult result)
    {
        BazusApi.LessonPlan[] retVal = ((IService1)(this)).EndAktualneNa7(result);
        return new object[] {
                retVal};
    }
    
    private void OnAktualneNa7Completed(object state)
    {
        if ((this.AktualneNa7Completed != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AktualneNa7Completed(this, new AktualneNa7CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AktualneNa7Async(string indeks, string date)
    {
        this.AktualneNa7Async(indeks, date, null);
    }
    
    public void AktualneNa7Async(string indeks, string date, object userState)
    {
        if ((this.onBeginAktualneNa7Delegate == null))
        {
            this.onBeginAktualneNa7Delegate = new BeginOperationDelegate(this.OnBeginAktualneNa7);
        }
        if ((this.onEndAktualneNa7Delegate == null))
        {
            this.onEndAktualneNa7Delegate = new EndOperationDelegate(this.OnEndAktualneNa7);
        }
        if ((this.onAktualneNa7CompletedDelegate == null))
        {
            this.onAktualneNa7CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAktualneNa7Completed);
        }
        base.InvokeAsync(this.onBeginAktualneNa7Delegate, new object[] {
                    indeks,
                    date}, this.onEndAktualneNa7Delegate, this.onAktualneNa7CompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginDodajWydarzenie(string indeks, System.DateTime date, string tytul_tekst, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDodajWydarzenie(indeks, date, tytul_tekst, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndDodajWydarzenie(System.IAsyncResult result)
    {
        return base.Channel.EndDodajWydarzenie(result);
    }
    
    private System.IAsyncResult OnBeginDodajWydarzenie(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string indeks = ((string)(inValues[0]));
        System.DateTime date = ((System.DateTime)(inValues[1]));
        string tytul_tekst = ((string)(inValues[2]));
        return ((IService1)(this)).BeginDodajWydarzenie(indeks, date, tytul_tekst, callback, asyncState);
    }
    
    private object[] OnEndDodajWydarzenie(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndDodajWydarzenie(result);
        return new object[] {
                retVal};
    }
    
    private void OnDodajWydarzenieCompleted(object state)
    {
        if ((this.DodajWydarzenieCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.DodajWydarzenieCompleted(this, new DodajWydarzenieCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void DodajWydarzenieAsync(string indeks, System.DateTime date, string tytul_tekst)
    {
        this.DodajWydarzenieAsync(indeks, date, tytul_tekst, null);
    }
    
    public void DodajWydarzenieAsync(string indeks, System.DateTime date, string tytul_tekst, object userState)
    {
        if ((this.onBeginDodajWydarzenieDelegate == null))
        {
            this.onBeginDodajWydarzenieDelegate = new BeginOperationDelegate(this.OnBeginDodajWydarzenie);
        }
        if ((this.onEndDodajWydarzenieDelegate == null))
        {
            this.onEndDodajWydarzenieDelegate = new EndOperationDelegate(this.OnEndDodajWydarzenie);
        }
        if ((this.onDodajWydarzenieCompletedDelegate == null))
        {
            this.onDodajWydarzenieCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDodajWydarzenieCompleted);
        }
        base.InvokeAsync(this.onBeginDodajWydarzenieDelegate, new object[] {
                    indeks,
                    date,
                    tytul_tekst}, this.onEndDodajWydarzenieDelegate, this.onDodajWydarzenieCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetWydarzenia(string indeks, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetWydarzenia(indeks, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    MobilePWSZService.wydarzenia[] IService1.EndGetWydarzenia(System.IAsyncResult result)
    {
        return base.Channel.EndGetWydarzenia(result);
    }
    
    private System.IAsyncResult OnBeginGetWydarzenia(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string indeks = ((string)(inValues[0]));
        return ((IService1)(this)).BeginGetWydarzenia(indeks, callback, asyncState);
    }
    
    private object[] OnEndGetWydarzenia(System.IAsyncResult result)
    {
        MobilePWSZService.wydarzenia[] retVal = ((IService1)(this)).EndGetWydarzenia(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetWydarzeniaCompleted(object state)
    {
        if ((this.GetWydarzeniaCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetWydarzeniaCompleted(this, new GetWydarzeniaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetWydarzeniaAsync(string indeks)
    {
        this.GetWydarzeniaAsync(indeks, null);
    }
    
    public void GetWydarzeniaAsync(string indeks, object userState)
    {
        if ((this.onBeginGetWydarzeniaDelegate == null))
        {
            this.onBeginGetWydarzeniaDelegate = new BeginOperationDelegate(this.OnBeginGetWydarzenia);
        }
        if ((this.onEndGetWydarzeniaDelegate == null))
        {
            this.onEndGetWydarzeniaDelegate = new EndOperationDelegate(this.OnEndGetWydarzenia);
        }
        if ((this.onGetWydarzeniaCompletedDelegate == null))
        {
            this.onGetWydarzeniaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWydarzeniaCompleted);
        }
        base.InvokeAsync(this.onBeginGetWydarzeniaDelegate, new object[] {
                    indeks}, this.onEndGetWydarzeniaDelegate, this.onGetWydarzeniaCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IService1 CreateChannel()
    {
        return new Service1ClientChannel(this);
    }
    
    private class Service1ClientChannel : ChannelBase<IService1>, IService1
    {
        
        public Service1ClientChannel(System.ServiceModel.ClientBase<IService1> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetAuthenticate(string login, string password, string PasswordHash, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = login;
            _args[1] = password;
            _args[2] = PasswordHash;
            System.IAsyncResult _result = base.BeginInvoke("GetAuthenticate", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndGetAuthenticate(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("GetAuthenticate", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetRegister(string login, string password, string mail, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = login;
            _args[1] = password;
            _args[2] = mail;
            System.IAsyncResult _result = base.BeginInvoke("GetRegister", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndGetRegister(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("GetRegister", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetPlan(string indeks, System.DateTime enteredDate, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = indeks;
            _args[1] = enteredDate;
            System.IAsyncResult _result = base.BeginInvoke("GetPlan", _args, callback, asyncState);
            return _result;
        }
        
        public BazusApi.LessonPlan EndGetPlan(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BazusApi.LessonPlan _result = ((BazusApi.LessonPlan)(base.EndInvoke("GetPlan", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetReset(string login, string mail, string passOld_passNew, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = login;
            _args[1] = mail;
            _args[2] = passOld_passNew;
            System.IAsyncResult _result = base.BeginInvoke("GetReset", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndGetReset(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("GetReset", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetNews(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetNews", _args, callback, asyncState);
            return _result;
        }
        
        public MobilePWSZService.News[] EndGetNews(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            MobilePWSZService.News[] _result = ((MobilePWSZService.News[])(base.EndInvoke("GetNews", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetHash(string login, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = login;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("GetHash", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetHash(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetHash", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetUpdatedPlan(string kierunek, string rok, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = kierunek;
            _args[1] = rok;
            System.IAsyncResult _result = base.BeginInvoke("GetUpdatedPlan", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetUpdatedPlan(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetUpdatedPlan", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginAktualneNa7(string indeks, string date, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = indeks;
            _args[1] = date;
            System.IAsyncResult _result = base.BeginInvoke("AktualneNa7", _args, callback, asyncState);
            return _result;
        }
        
        public BazusApi.LessonPlan[] EndAktualneNa7(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            BazusApi.LessonPlan[] _result = ((BazusApi.LessonPlan[])(base.EndInvoke("AktualneNa7", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginDodajWydarzenie(string indeks, System.DateTime date, string tytul_tekst, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = indeks;
            _args[1] = date;
            _args[2] = tytul_tekst;
            System.IAsyncResult _result = base.BeginInvoke("DodajWydarzenie", _args, callback, asyncState);
            return _result;
        }
        
        public string EndDodajWydarzenie(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("DodajWydarzenie", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetWydarzenia(string indeks, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = indeks;
            System.IAsyncResult _result = base.BeginInvoke("GetWydarzenia", _args, callback, asyncState);
            return _result;
        }
        
        public MobilePWSZService.wydarzenia[] EndGetWydarzenia(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            MobilePWSZService.wydarzenia[] _result = ((MobilePWSZService.wydarzenia[])(base.EndInvoke("GetWydarzenia", _args, result)));
            return _result;
        }
    }
}
